##### General Properties #####
mysql_data_delimiter: ^

##### Database Properties #####
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gpporgs?driver=com.mysql.jdbc.Driver&serverTimezone=UTC
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1035290053103-56crsjin0a9bcbdphqqqd3mhtjh3rtdv.apps.googleusercontent.com
            client-secret: 1wtwcqwy_eWL_jVhHQ1TPJyt
